version: '3.6'

services:
  app:
    container_name: adm_videos_app
    image: igorgomes96/fc3-admin-catalogo-de-videos-c-sharp:latest
    restart: unless-stopped
    volumes:
      - ./src/FC.Codeflix.Catalog.Api/gcp_credentials.json:/app/gcp_credentials.json
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - GOOGLE_APPLICATION_CREDENTIALS=gcp_credentials.json
    depends_on:
      - fc.codeflix.catalog.fb
      - rabbitmq
      - keycloak
      - filebeat
    labels:
      filebeat_collector: true
      decode_log_event_to_json_object: true

  fc.codeflix.catalog.fb:
    container_name: catalogdb
    hostname: catalogdb
    image: mysql
    volumes:
      - .docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: C0D3fl1X.@

  rabbitmq:
    container_name: adm_videos_rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
      - .docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - .docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    environment:
      - RABBITMQ_DEFAULT_USER=adm_videos
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - 15672:15672
      - 5672:5672

  keycloak:
    container_name: adm_videos_keycloak
    image: quay.io/keycloak/keycloak:20.0.3
    hostname: keycloak
    restart: unless-stopped
    volumes:
      - .docker/keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL_HOST=catalogdb
      - KC_DB_URL_PORT=3306
      - KC_DB_SCHEMA=keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=C0D3fl1X.@
    ports:
      - 8080:8080
    command:
      - start-dev --import-realm --hostname-url=http://keycloak:8080
    depends_on:
      - fc.codeflix.catalog.fb

  filebeat:
    container_name: adm_videos_filebeat
    image: docker.elastic.co/beats/filebeat:7.17.10
    command: filebeat -e -strict.perms=false
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
      - .docker/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - .docker/filebeat:/usr/share/filebeat/data:rw                    # Persistence data
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure

networks:
  default:
    name: service_catalog
    external: true